add support n-graphs + pull request
GraphLabsSuite/TaskCore.Template pull request #17
Opened 2019-12-02 18:58 UTC by AnastasiiaRazheva

2019-12-02 19:03 UTC, AnastasiiaRazheva reviewed
during pull request 
in **src/redux/rootReducer.ts** 
**import { IGraphView, IMatrixView } from '..';**  
->
**import { IGraphView, IMatrixView, INGraphsView } from '..';**

2019-12-02 20:23 UTC, eakarpov requested changes

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    graph = result.graph;
Для чего формируются и граф и н-граф? Это дублирующая информация.

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +        const namesForVertices = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "g", "k", "l", "m", "n", "o", "p"];
хардкод явно не нужен. Например можно использовать функцию String.fromCharCode

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                let graphInCashe: IGraph<IVertex, IEdge> = new Graph() as unknown as IGraph<IVertex, IEdge>;
cache, not cashe

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
так как счетчик независимый, нужна null-check проверка объекта графа

2019-12-02 20:23 UTC, eakarpov commented on src/models/ngraphs.ts
> +export type INGraphsView = IGraph<IVertex, IEdge>[];
Array<IGraph<IVertex, IEdge>>

2019-12-02 20:23 UTC, eakarpov commented on src/models/ngraphs.ts
> +export const ngraphs = 'ngraphs';
можно посмотреть, новые версии тайпскрипта могут по идее работать и только с типовой информацией.

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +            let numberOfGraphs = JSON.parse(data.count);
почему let?

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +        let graph:IGraph<IVertex, IEdge> = = new Graph() as unknown as IGraph<IVertex, IEdge>;
почему let?

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                vertices.forEach((v: any) => {
IVertex мб а не any?

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
IEdge вместо any?

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                vertices.forEach((v: any) => {
или string если это строка

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
или string если это строка

2019-12-02 20:23 UTC, eakarpov commented on src/redux/ngraphs/reducers.ts
> +export default (state: INGraphsView = initialState, action: INGraphsActionFill): INGraphsView => {
у тебя графы  только readonly будут? как взаимодействовать с их моделями если они только полностью списком перезаписываются

2019-12-02 20:23 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    ngraphs = result.ngraphs;
может быть по аналогии с графом использовать подход es-модулей? Ну это просто на подумать

2019-12-02 20:26 UTC, svtz commented on src/components/Template/index.tsx
> +        const namesForVertices = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "g", "k", "l", "m", "n", "o", "p"];
не-не, задумка такая что я в апи могу буквы прислать! Вообще тут не надо в буквы ничего пока преобразовывать))
Давайте пока без букв, в след семестре проверим и если что кто-нибудь сделает чтоб работало

2019-12-02 20:27 UTC, eakarpov commented on src/components/Template/index.tsx
> +        const namesForVertices = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "g", "k", "l", "m", "n", "o", "p"];
@svtz что за буквы? с именами? а зачем их хардкодить все равно не понимаю

2019-12-02 20:31 UTC, eakarpov commented on src/components/Template/index.tsx
> +        const namesForVertices = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "g", "k", "l", "m", "n", "o", "p"];
обсудили с @svtz - выпиливаем массив, он приходить будет с сервера

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    ngraphs = result.ngraphs;
Я не поняла.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    graph = result.graph;
В граф добавляются (сливаются) все 3 графа, позже он добавляется в graphModel. Это намного упростит отрисовку данных графов, и также может понадобится для дальнейшей работы модулей. 
В n-graph**s**  графы добавляются как отдельные элементы массива. Это необходимо для работы самого модуля и анализа графов на изоморфизм.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +        const namesForVertices = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "g", "k", "l", "m", "n", "o", "p"];
@eakarpov Буквы нужны для переименования вершин графов, чтобы визуально было легко отличить один от другого. Также в изначальном варианте Ани не было вершин с одинаковыми именами - я не уверена, что модуль не сломается, если вершины будут называться одинаково. Логику анализа на изоморфизм я не меняла.
Давайте вы сначала допилите сервер, чтобы он буквы присылал, а уже потом удалите массив. Удалить несложно.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +        let graph:IGraph<IVertex, IEdge> = = new Graph() as unknown as IGraph<IVertex, IEdge>;
да мне не критично, можно и не let.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +            let numberOfGraphs = JSON.parse(data.count);
да мне не критично, можно и не let.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                let graphInCashe: IGraph<IVertex, IEdge> = new Graph() as unknown as IGraph<IVertex, IEdge>;
ок.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
А можно поподробнее?

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                vertices.forEach((v: any) => {
Я делала по аналогии с graphManager - там стоит any.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
Я делала по аналогии с graphManager - там стоит any.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/models/ngraphs.ts
> +export type INGraphsView = IGraph<IVertex, IEdge>[];
Хорошо, если так правильнее.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/models/ngraphs.ts
> +export const ngraphs = 'ngraphs';
Я вообще не поняла о чём ты. Я делала по аналогии с graph и matrix.

2019-12-02 21:50 UTC, AnastasiiaRazheva commented on src/redux/ngraphs/reducers.ts
> +export default (state: INGraphsView = initialState, action: INGraphsActionFill): INGraphsView => {
Для начала хочу сделать хотя бы readonly, если взлетит - потом можно будет и логику накручивать.

2019-12-02 22:00 UTC, svtz commented on src/components/Template/index.tsx
> +                    graph = result.graph;
ну это... не очень универсальное поведение. Мне кажется, не каждому модулю подойдёт сливание всех графов в один. Я бы всё-таки убрал из шаблона это сливание. Но его вполне можно сделать на уровне самого модуля

2019-12-02 22:03 UTC, svtz commented on src/components/Template/index.tsx
> +        const namesForVertices = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "g", "k", "l", "m", "n", "o", "p"];
опять-таки это очень похоже на внутренние костыли модуля))

2019-12-05 06:07 UTC, eakarpov commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
Сначала проверяешь что объект существует, потом поле у него вызываешь

2019-12-05 06:08 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    ngraphs = result.ngraphs;
Ну вот ты делаешь через редукс, а один граф Эллина переделала на es модуль. Это позволяет работать с моделью графа IGraph со всеми имеющимися методами, а не с жсон представлением

2019-12-08 10:57 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    graph = result.graph;
Я правильно понимаю, что у нас objectData.data[0].type будет равен 'n-graphs' только в случае если открыт модуль изоморфизма?

2019-12-08 10:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
Хорошо

2019-12-08 10:59 UTC, svtz commented on src/components/Template/index.tsx
> +                    graph = result.graph;
нет конечно, могут ещё какие-то модули появиться поддерживающие n графов

2019-12-09 08:03 UTC, eakarpov commented on src/components/Template/index.tsx
> +        let graph:IGraph<IVertex, IEdge> = = new Graph() as unknown as IGraph<IVertex, IEdge>;
И JSON.parse - так не приводи данные плиз, к числу приводи через parseInt / parseFloat

2019-12-09 08:06 UTC, eakarpov requested changes

2019-12-09 08:06 UTC, eakarpov commented on src/components/Template/index.tsx
> +            let numberOfGraphs = JSON.parse(data.count);
вот здесь вот лучше parseInt

2019-12-09 08:06 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    ngraphs = this.nGraphsManager(objectData.data[0].value);
так и нет проверки на null point

2019-12-09 08:06 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    let vertices = data.graphs[i].vertices;
проверки на null point - ?

2019-12-09 08:06 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    let graphInCaсhe: IGraph<IVertex, IEdge> = new Graph() as unknown as IGraph<IVertex, IEdge>;
let -> const

2019-12-09 08:07 UTC, eakarpov commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
не исправлено

2019-12-09 08:07 UTC, eakarpov commented on src/models/ngraphs.ts
> +export const ngraphs = 'ngraphs';
оставим пока так

2019-12-09 08:08 UTC, eakarpov commented on src/components/Template/index.tsx
> +                vertices.forEach((v: any) => {
стоит везде избегать any. думаю здесь имеется в виду строка

2019-12-09 08:08 UTC, eakarpov commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
аналогично предыдущему

2019-12-09 08:08 UTC, eakarpov commented on src/redux/ngraphs/reducers.ts
> +export default (state: INGraphsView = initialState, action: INGraphsActionFill): INGraphsView => {
ок давай так

2019-12-09 19:09 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
Я может как-то не так закоммитила, но у меня это выглядит так: 
```
if (data) {
   let numberOfGraphs = parseInt(data.count, 10);
   if (numberOfGraphs){
      for (let i = 0; i < numberOfGraphs; i++) {
```
https://github.com/GraphLabsSuite/Core.Template/commit/23080a8424d38e9edf9ea3d10ee97bb49088a8f3

2019-12-09 19:11 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +        let graph:IGraph<IVertex, IEdge> = = new Graph() as unknown as IGraph<IVertex, IEdge>;
Поменяю на 
`let numberOfGraphs = parseInt(data.count, 10);`

2019-12-09 19:15 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                vertices.forEach((v: any) => {
Хорошо

2019-12-09 19:29 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
Я не знаю на что тут менять: 
В данные переменные передаются объекты из objectData, в который записывается результат JSON.parse(data||"null"). 

И если с vertices понятно, что передаётся просто массив имён, и можно обрабатывать это как string, то в случае с edges - это объекты которые имеют по крайней мере 2 свойства (e.source, e.target). Как это обрабатывать - я не знаю, как string вроде-бы не получиться, и я не думаю что JSON.parse() знает что-то про IEdge и возращает объекты этого класса. 

Прошу также заметить, что и в graphManager это обрабатывается как **any**. Боюсь я не смогу тут написать красивей и изящней чем вы.

2019-12-09 19:32 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    ngraphs = result.ngraphs;
Я не знаю что такое "редукс", я не знаю что такое "es модуль", я не вижу где в коде "один граф Эллина переделала на es модуль". Я абсолютно не представляю что ты тут от меня хочешь, и на что опираться чтобы выполнить твою просьбу.

2019-12-09 19:37 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    ngraphs = this.nGraphsManager(objectData.data[0].value);
Проверка делается выше, до case
`if (objectData && objectData.data[0].type) {`
Я опиралась на реализованную вами обработку 1ого графа, там ничего подобного нет:
```
                case 'graph':
                    graph = this.graphManager(objectData.data[0].value);
                    init(graph);
```

2019-12-09 19:38 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    let vertices = data.graphs[i].vertices;
Чем тебе не нравиться проверка на null ? 
`if (numberOfGraphs){`

2019-12-09 19:45 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    let graphInCaсhe: IGraph<IVertex, IEdge> = new Graph() as unknown as IGraph<IVertex, IEdge>;
Это временная, разовая переменная, зачем её делать const? В вашем коде подобные переменные также объявляются как **let**. 

Объясни пожалуйста зачем вы вообще везде пихаете const - который предполагает, что объект не будет меняться, даже когда он тут-же в следующей строчке меняется: 
```
let graphInCaсhe: IGraph<IVertex, IEdge> = ...
   graphInCaсhe.addVertex(new Vertex(v));
```

2019-12-09 19:53 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    let graphInCaсhe: IGraph<IVertex, IEdge> = new Graph() as unknown as IGraph<IVertex, IEdge>;
Все, что не меняется, надо делать const. Это позволит избежать возможности непредвиденных присваиваний в коде тому, чему не надо. В твоем примере объект НЕ меняется, поэтому и нужно его назначить const. Меняется лишь свойство объекта. Объект и вообще все что угодно меняется только при присваивании.
```typescript
// здесь меняется объект
let a = { a: 2 };
a = { a: 3};
// здесь не меняется объект
const b = { a: 2 };
b.a = 3;
```

2019-12-09 19:54 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    let vertices = data.graphs[i].vertices;
это не проверка на null. Это вообще избыточный код, потому что цикл от 0 до 0 выполнится 0 раз.

2019-12-09 19:55 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    ngraphs = this.nGraphsManager(objectData.data[0].value);
Если у тебя нет поля data или этот массив пустой, то при обращении к свойству type уже произойдет ошибка нулевой ссылки. Нужно проверять на возможный нулл в объекте data[0], и если нет выше проверки на длину массива, то и на пустой массив.

2019-12-09 19:56 UTC, eakarpov commented on src/components/Template/index.tsx
> +                    ngraphs = result.ngraphs;
Ты пишешь на React, и не знаешь, что такое ES-модуль и Redux? Это не в твою пользу, почитай, это полезная информация.

2019-12-09 19:58 UTC, eakarpov commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
То что написано в другом месте ни о чем не говорит. Мы учимся писать хороший код, поэтому придирки вполне обоснованы. Надо понять, что за тип в массиве edges, подозреваю, что это вполне коррелирует с интерфейсом IEdge. Если нет, это либо вопрос к интерфейсу, либо к формату присланных данных, что можно обсудить. Однако мне кажется, что там все в порядке с ним.

2019-12-09 19:58 UTC, eakarpov commented on src/components/Template/index.tsx
> +        let graph:IGraph<IVertex, IEdge> = = new Graph() as unknown as IGraph<IVertex, IEdge>;
Ок, верно. Только let зачем?

2019-12-09 19:59 UTC, eakarpov commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
И где здесь null проверка на data.graphs[i]?

2019-12-15 18:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                let vertices = data.graphs[i].vertices;
Добавила.
```
        if (data && data.count) {
            const numberOfGraphs = parseInt(data.count, 10);
            for (let i = 0; i < numberOfGraphs; i++) {
                if (data.graphs[i]){
```

2019-12-15 18:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +        let graph:IGraph<IVertex, IEdge> = = new Graph() as unknown as IGraph<IVertex, IEdge>;
Поправила.

2019-12-15 18:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                edges.forEach((e: any) => {
Хорошо, надеюсь что так ))

2019-12-15 18:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    ngraphs = result.ngraphs;
Изучаю, но это будет не быстро ...

2019-12-15 18:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    ngraphs = this.nGraphsManager(objectData.data[0].value);
Добавила в общие проверки, теперь:
` if (objectData && objectData.data[0] && objectData.data[0].type) {`

2019-12-15 18:59 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    let vertices = data.graphs[i].vertices;
Переделала: 
```
        if (data && data.count) {
            const numberOfGraphs = parseInt(data.count, 10);
            for (let i = 0; i < numberOfGraphs; i++) {
                if (data.graphs[i]){
```

2019-12-15 19:05 UTC, AnastasiiaRazheva commented on src/components/Template/index.tsx
> +                    let graphInCaсhe: IGraph<IVertex, IEdge> = new Graph() as unknown as IGraph<IVertex, IEdge>;
Теперь стало понятней, спасибо.

2019-12-15 19:49 UTC, eakarpov approved these changes

2019-12-15 19:49 UTC, merged