Update graphManager
GraphLabsSuite/TaskCore.Template pull request #38
Opened 2021-04-24 14:36 UTC by ayarabaeva

2021-04-25 09:51 UTC, AMusatova requested changes
В graphManager надо убрать [0] у name и у weightLabel. Они остались в 1ом и в 5ом if, чтобы была возможность не однозначного задания.

2021-04-25 10:00 UTC, AMusatova approved these changes

2021-04-25 10:01 UTC, AMusatova approved these changes

2021-04-26 15:12 UTC, svtz requested changes

2021-04-26 15:12 UTC, svtz commented on src/components/Template/index.tsx
> +                if (e.name && e.weightLabel && e.isDirected){
3 флага => 9 возможных сочетаний. Вижу только 8. Что-то пропущено.

2021-04-26 15:22 UTC, svtz approved these changes

2021-04-26 15:22 UTC, merged